# Generated by Django 2.2.1 on 2019-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190524_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
