# Generated by Django 2.2.1 on 2019-05-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20190524_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='count',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='newUrl',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='user',
        ),
    ]
